name: Test

on: 
  workflow_dispatch:

jobs:
  version:
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    secrets: inherit
    with:
      increment: false
      build-var: BUILD_NUMBER

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Create dummy files
        run: |
          mkdir build
          mkdir build/test
          echo "akjdhaksdhkasjhdkasjhd" >> build/a.txt
          echo "1871236468723648234" >> build/b.txt
          echo "sohjfiosdhgfoisdhfgos" >> build/c.txt
          echo "lolololololol" >> build/test/d.txt

      - name: Upload to S3 but keep the latest 5 only
        uses: starburst997/s3-upload-action@v1
        with:
          key-id: ${{ secrets.S3_KEY_ID }}
          secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          region: ${{ secrets.S3_REGION }}
          endpoint: ${{ secrets.S3_ENDPOINT }}
          bucket: ${{ secrets.S3_BUCKET }}

          src-dir: 'build'
          dst-dir: 'apps/test/internal'
          dst-version: '${{ needs.version.outputs.version }}'
          keep: 5